#!/bin/bash

# Container Exit
cexit() {
	echo 'Container Terminated'
	exit 0
}

DATA=/home/apk/data

# If not mounted, create data directory
if [[ ! -d ${DATA} ]]; then
	sudo -HEu apk mkdir -p ${DATA}
else 
	chown -R apk:abuild ${DATA}
	chmod 777 ${DATA}
fi

# Failsafe check, should never run
if [[ -d /home/apk/.ssh ]] && [[ ! -L /home/apk/.ssh ]]; then
	# .ssh already exists, weird...
	# Move to data and create symbolic link
	mv /home/apk/.ssh ${DATA}
	ln -s /home/apk/data/.ssh /home/apk/.ssh
fi

if [ ! -d ${DATA}/.ssh ]; then
	sudo -HEu apk mkdir -p ${DATA}/.ssh
	ln -s /home/apk/data/.ssh /home/apk/.ssh
else 
	if [[ ! -L /home/apk/.ssh ]]; then
		ln -s /home/apk/data/.ssh /home/apk/.ssh
	fi 
fi


if [ ! -d ${DATA}/.apk ]; then
	sudo -HEu apk mkdir -p ${DATA}/.apk
	cp -fra /etc/apk/keys ${DATA}/.apk/
	rm -rf /etc/apk/keys
	ln -s ${DATA}/.apk/keys /etc/apk/keys
else
	cp -ra /etc/apk/keys ${DATA}/.apk/
	rm -rf /etc/apk/keys
	ln -s ${DATA}/.apk/keys /etc/apk/keys
fi

if [ ! -d ${DATA}/.abuild ]; then
	sudo -HEu apk mkdir -p ${DATA}/.abuild
	ln -s /home/apk/data/.abuild /home/apk/.abuild
else 
	if [[ ! -L /home/apk/.abuild ]]; then
		ln -s /home/apk/data/.abuild /home/apk/.abuild
	fi
fi

if [ ! -f ${DATA}/.abuild/abuild.conf ]; then
	cp /etc/abuild.conf ${DATA}/.abuild/abuild.conf
	rm -f /etc/abuild.conf
	ln -s ${DATA}/.abuild/abuild.conf /etc/abuild.conf
	chown apk:abuild ${DATA}/.abuild/abuild.conf
	chmod 777 ${DATA}/.abuild/abuild.conf
else
	rm -f /etc/abuild.conf
	ln -s ${DATA}/.abuild/abuild.conf /etc/abuild.conf
	chown apk:abuild ${DATA}/.abuild/abuild.conf
	chmod 777 ${DATA}/.abuild/abuild.conf
fi

if [[ ! -f /home/apk/.gitconfig ]]; then
	touch ${DATA}/.gitconfig
	ln -s /home/apk/data/.gitconfig /home/apk/.gitconfig
	git config --global user.name ${GIT_USER}
	git config --global user.email ${GIT_EMAIL}
else 
	rm /home/apk/.gitconfig
	ln -s /home/apk/data/.gitconfig /home/apk/.gitconfig
fi

if [[ ! -d ${DATA}/aports ]]; then
	sudo -HEu apk git clone ${REPO_URL} ${DATA}/aports
	cd ${DATA}/aports
	sudo -HEu apk git remote add upstream https://github.com/alpinelinux/aports.git
	sudo -HEu apk git fetch upstream
	sudo -HEu apk git checkout master
	sudo -HEu apk git merge upstream/master
	sudo -HEu apk git push origin master
else 
	cd ${DATA}/aports
	sudo -HEu apk git fetch upstream
	sudo -HEu apk git checkout master
	sudo -HEu apk git merge upstream/master
	sudo -HEu apk git push origin master
fi

# Upgrade Image
apk upgrade --update-cache --no-cache --available

if [[ ! -f /etc/profile.d/term.sh ]]; then
	echo 'export TERM=xterm' > /etc/profile.d/term.sh
fi

if [[ ! -f /etc/profile.d/data.sh ]]; then
	echo 'export DATA=/home/apk/data' > /etc/profile.d/data.sh
fi

if [[ ! -f /etc/profile.d/alias.sh ]]; then
	echo "alias ll='ls -la'" > /etc/profile.d/alias.sh
fi

trap cexit TERM

while true; do
	sleep 100 &
	wait $!
done

# EOF