#!/bin/bash
set -e

if [ -d "/home/sdk/.abuild" ]; then
    sudo cp ~/.abuild/*.pub /etc/apk/keys
else
    abuild-keygen -a -n
    sudo cp ~/.abuild/*.pub /etc/apk/keys
fi

if [ -z "${1}" ]; then
	exec /bin/bash --login
else 
	exec "$@"
fi
