#!/bin/bash
set -e

if [ -d "/home/sdk/.abuild" ]; then
    sudo cp ~/.abuild/*.pub /etc/apk/keys
else
    abuild-keygen -a -n
    sudo cp ~/.abuild/*.pub /etc/apk/keys
fi

if [ ! -d ~/aports ]; then
	git clone --recursive https://github.com/${GITHUB_USER}/aports.git
	cd ~/aports
	git remote add upstream https://github.com/alpinelinux/aports.git
	cd -
fi

if [ -z "${1}" ]; then
	exec /bin/bash --login
else 
	exec "$@"
fi
